//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonacionSangre.DataModel.BDContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class aviso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aviso()
        {
            this.postulacion = new HashSet<postulacion>();
        }
    
        public int idAviso { get; set; }
        public int idUsuarioSolicitante { get; set; }
        public string nombre { get; set; }
        public int idSangre { get; set; }
        public Nullable<int> idRequerimiento { get; set; }
        public string critico { get; set; }
        public decimal cantidad { get; set; }
        public string descripcion { get; set; }
        public byte[] imagen { get; set; }
        public System.DateTime fechaVigencia { get; set; }
        public int idDepartamento { get; set; }
        public int idCiudad { get; set; }
    
        public virtual requerimiento requerimiento { get; set; }
        public virtual tipoSangre tipoSangre { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<postulacion> postulacion { get; set; }
    }
}
