//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonacionSangre.DataModel.BDContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DonacionEntities : DbContext
    {
        public DonacionEntities()
            : base("name=DonacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aviso> aviso { get; set; }
        public virtual DbSet<ciudad> ciudad { get; set; }
        public virtual DbSet<departamento> departamento { get; set; }
        public virtual DbSet<formulario> formulario { get; set; }
        public virtual DbSet<perfil> perfil { get; set; }
        public virtual DbSet<postulacion> postulacion { get; set; }
        public virtual DbSet<requerimiento> requerimiento { get; set; }
        public virtual DbSet<tipoSangre> tipoSangre { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
